MRX_ShopCatalog {
 m_aItems {
  MRX_ShopItem "{6A89197001F860AD}" {
   m_sId "field_dressing"
   m_sPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_sCategory "Medical"
   m_iPrice 20
  }
  MRX_ShopItem "{6A89197001F85175}" {
   m_sId "tourniquet"
   m_sPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_sCategory "Medical"
   m_iPrice 40
  }
  MRX_ShopItem "{6A89197001F85C2E}" {
   m_sId "morphine"
   m_sPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_sCategory "Medical"
   m_iPrice 60
  }
  MRX_ShopItem "{6A89197001F84BF9}" {
   m_sId "map"
   m_sPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_sCategory "Equipment"
   m_iPrice 30
  }
  MRX_ShopItem "{6A89197001F8B42C}" {
   m_sId "compass"
   m_sPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_sCategory "Equipment"
   m_iPrice 50
  }
  MRX_ShopItem "{6A89197001F8A019}" {
   m_sId "watch"
   m_sPrefab "{6FD6C96121905202}Prefabs/Items/Equipment/Watches/Watch_Vostok.et"
   m_sCategory "Equipment"
   m_iPrice 80
  }
  MRX_ShopItem "{6A89197001F8AEF7}" {
   m_sId "binoculars"
   m_sPrefab "{0CF54B9A85D8E0D4}Prefabs/Items/Equipment/Binoculars/Binoculars_M22/Binoculars_M22.et"
   m_sCategory "Equipment"
   m_iPrice 150
  }
 }
}