PersistenceSystemConfig : "{B76E7F1AF7A5D00C}Configs/Systems/Persistence/GameMode/GameMaster.conf" {
 Storages {
  GamemodeStorage "{6A888CDFB7FC60F0}" {
   Database "{6624ADA9A88DA0F6}"
  }
 }
 Collections {
  PersistenceCollection "{6A888CDF8D8247E6}" {
   Name "MarxSpike"
   Storage "{6A888CDFB7FC60F0}"
  }
 }
 Configurations {
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Gameplay {
     Configurations {
      StatePersistenceConfig "{6A888CDF9520320C}" {
       Collection "{6A888CDF8D8247E6}"
       Serializer MRX_SpikeWalletSerializer "{6A888CDFEB7ECBC7}" {
       }
      }
     }
    }
   }
  }
 }
}