SystemSettings : "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{65DC893A38833A14}" {
   Config "{B66C629E4CE9965D}Configs/Marx/Spike/MRX_SpikePersistence.conf"
  }
 }
}