SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  MRX_MarxSystem "{6A88FD9099EB0B30}" {
   m_sSettingsConfig "{A520D015366C7F35}Configs/Marx/MRX_Settings.conf"
  }
 }
}