SystemSettings : "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{65DC893A38833A14}" {
   Config "{DB6F364D2E1F9EB2}Configs/Marx/Persistence/MRX_GameMasterPersistence.conf"
  }
 }
}