PersistenceSystemConfig : "{B76E7F1AF7A5D00C}Configs/Systems/Persistence/GameMode/GameMaster.conf" {
 Storages {
  GamemodeStorage "{6A891488C067D378}" {
   Database "{6624ADA9A88DA0F6}"
  }
 }
 Collections {
  PersistenceCollection "{6A891488C0643D40}" {
   Name "MarxWallets"
   Storage "{6A891488C067D378}"
  }
 }
 Configurations {
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Gameplay {
     Configurations {
      StatePersistenceConfig "{6A891488C0640FD6}" {
       Collection "{6A891488C0643D40}"
       Serializer MRX_WalletStateSerializer "{6A891488C06468A1}" {
       }
      }
     }
    }
   }
  }
 }
}